server:
  port: 8080
spring:
  application:
    name: ms-registry
eureka:
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false       #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:  #指定Eureka Server的地址，它是一个URL，用于告诉Eureka客户端应该连接到哪个Eureka服务器
      defaultZone: http://localhost:8080/eureka/