server:
  port: 80
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置注册中心进行动态路由功能
          lower-case-service-id: true # 将服务名称转为小写
      routes: #配置路由,可以有多个路由配置
        - id: ms-diners         #路由的ID,程序员自己写,要求唯一
          uri: lb://ms-diners   #gateway 最终访问的 url = uri + Path
          predicates:
            - Path=/diners/**
          filters:
            - StripPrefix=1
        - id: ms-oauth2-server
          uri: lb://ms-oauth2-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ms-seckill
          uri: lb://ms-seckill
          predicates:
            - Path=/seckill/**
          filters:
            - StripPrefix=1
        - id: ms-follow
          uri: lb://ms-follow
          predicates:
            - Path=/follow/**
          filters:
            - StripPrefix=1
        - id: ms-feeds
          uri: lb://ms-feeds
          predicates:
            - Path=/feeds/**
          filters:
            - StripPrefix=1
        - id: ms-points
          uri: lb://ms-points
          predicates:
            - Path=/points/**
          filters:
            - StripPrefix=1
        - id: ms-restaurants
          uri: lb://ms-restaurants
          predicates:
            - Path=/restaurants/**
          filters:
            - StripPrefix=1

secure:
  ignore:
    urls: # 配置白名单路径
      - /actuator/**
      - /auth/oauth/**
      - /diners/signin
      - /diners/send
      - /diners/checkPhone
      - /diners/register
      - /seckill/add
      - /restaurants/detail

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}